function generate_repository_structure_dot_file(nodes, html_loc, out_dir)
% Analyses the repository file structyre and writes this information into a
% dot file so that a graph can be generated by graphviz.
%
% Example: generate_repository_structure_dot_file(nodes, html_loc, out_dir)

for eua = length(nodes):-1:1
    node_places{eua} = nodes(eua).place;
    node_colours{eua} = nodes(eua).html_colour;
end %for
[unique_places, ia, ~]= unique(node_places);
unique_colours = node_colours(ia);

inst = cell(1);
inst{1,1} = 'digraph "Root" {';
inst{2,1} = '';
inst{3,1} = 'rankdir="LR"';
inst{4,1} = 'concentrate=true';
inst{5,1} = 'fontcolor=black';
inst{6,1} = 'overlap=false';
inst{7,1} = 'splines=ortho';
inst{8,1} = 'sep=0.2';
inst{9,1} = 'root="Root"';
inst{10,1} = 'nodesep=0.2';
inst{11,1} = 'ranksep=0.2';
inst{12,1} = 'K=0.01';
inst{13,1} = '"Root"[shape=tripleoctagon,fontname=Bold]';

all_places = {};
for nse = 1:length(unique_places)
    temp_locs = strfind(unique_places{nse}, '@');
    temp_place = regexprep(unique_places{nse}, '@', '>');
    temp_place_html = regexprep(unique_places{nse}, '@', '&gt;');
    temp_colour = unique_colours{nse};
    if ~isempty(temp_locs)
        folder_label = unique_places{nse}(temp_locs(end) +1:end);
        parent_name = regexprep(unique_places{nse}(1:temp_locs(end) -1), '@', '>');
        inst = cat(1, inst,cellstr(strcat('"',temp_place,'"[fillcolor="',...
            temp_colour,'",style=filled,len=0.5,',...
            ' URL="',html_loc , '/',temp_place_html ,'.html",',...
            'label="', folder_label ,'"',...
            ' target="_top"];')));
        inst = cat(1,inst,cellstr(strcat('"',parent_name, '" -> "',temp_place,'"')));
        more_places = cell(2*(length(temp_locs)-1),1);
        for hewd = length(temp_locs)-1:-1:1
            parent_name = temp_place(1:temp_locs(hewd) -1);
            child_name = temp_place(1:temp_locs(hewd +1) -1);
            inst = cat(1,inst,cellstr(strcat('"',parent_name, '" -> "', child_name,'"')));
            more_places{2 * hewd -1} = parent_name;
            more_places{2 * hewd} = child_name;
        end %for
        all_places = cat(1, all_places, more_places);
    end %if
end %for

% This is to cater for the case where some of the intermediate folders in
% the structure have no code in them.
all_p = unique(all_places);
empty_folders = setdiff(all_p, regexprep(unique_places, '@', '>'));
for hse = 1:length(empty_folders)
    temp_locs = strfind(empty_folders{hse}, '>');
    if ~isempty(temp_locs)
        folder_label = empty_folders{hse}(temp_locs(end) +1:end);
        inst = cat(1, inst,cellstr(strcat('"',empty_folders{hse},'"[',...
            'style=filled,len=0.5,',...
            'label="', folder_label ,'"',...
            ' target="_top"];')));
    end %if
end %for

inst = cat(1,inst,cellstr('}'));

% Writing the file
write_out_data(inst, fullfile(out_dir, 'Repository.dot'))